### ISSUE TITLE
Age warning screen button cannot be pressed

### ISSUE THREAD

**Issue by pardeike** [agg23/Sila#26]
On channels that display a mature warning I wasn’t able to click on the button that dismisses that screen. Audio plays but video starts after that screen. It toggles the bottom area below the video instead.

**Comment by agg23** [comment]
This was hopefully fixed by 465a218771f0fa81d4562ca962e77bed5a83af7c and f229360b4c7f09a85adfd6bcc9cf2b7547db4112, but it hasn't been released to the App Store yet.

I apologize for the issue. In the meantime, you may be able to load streams with the same content restriction over and over again and the detection may take effect. I believe this issue arises when the page takes longer to load.

**Comment by pardeike** [comment]
As a note, I am only using the TestFlight version as I have a non-US Apple ID

**Comment by agg23** [comment]
Ah, well that might be your issue too. TestFlight has not been maintained since the public release, and is missing several key fixes.

**Comment by pardeike** [comment]
Would be nice to have TestFlight until the European AppStore goes live.
